// Generated by CoffeeScript 1.6.3
(function() {
  var addLineBreak, fs;

  fs = require('fs');

  exports.index = function(req, res) {
    res.render("index", {
      title: "CSV Converter"
    });
  };

  /*"/Mg9Nfp" is our substring used to identify where a new line should be placed.*/


  addLineBreak = function(str) {
    return str.replace(/Mg9Nfp/g, "\r\n");
  };

  exports.csv = function(req, res) {
    var str;
    str = addLineBreak(req.body.csvtext);
    fs.unlink("name.csv");
    fs.writeFile("name.csv", str, {
      encoding: 'utf8',
      mode: 438,
      flag: 'a'
    });
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
