// Generated by CoffeeScript 1.7.1
(function() {
  var addHTMLLineBreak, addLineBreak, fs, secondPageOne, secondPageTwo;

  fs = require('fs');

  exports.index = function(req, res) {
    res.render("index", {
      title: "CSV Converter"
    });
  };


  /*"/Mg9Nfp" is our substring used to identify where a new line should be placed. */

  addLineBreak = function(str) {
    return str.replace(/Mg9Nfp/g, "\r\n");
  };

  addHTMLLineBreak = function(str) {
    return str.replace(/Mg9Nfp/g, "<br />\n");
  };

  secondPageOne = "<!DOCTYPE html>\n <html>\n <head>\n <title></title>\n </head>\n <body>\n <h1>Your CSV: </h1>\n <div style='border: 1px solid; border-color: dimgray; background-color: lightgray'>";

  secondPageTwo = "\n </div> </body>\n </html>";

  exports.csv = function(req, res) {
    var CSVstr, HTMLstr;
    CSVstr = addLineBreak(req.body.csvtext);
    HTMLstr = addHTMLLineBreak(req.body.csvtext);
    fs.unlink("name.csv");
    fs.writeFile("name.csv", CSVstr, {
      encoding: 'utf8',
      mode: 438,
      flag: 'a'
    });
    res.send(secondPageOne + HTMLstr + secondPageTwo);
  };

}).call(this);

//# sourceMappingURL=index.map
